#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# This updates our edk2-based include files in include/efi/
set -eu

declare -a CPUS
CPUS=(AARCH64 ARM EBC IA32 RISCV64 X64)

run_gcc() {
	gcc "${@}" -MM -x c -\
		-Iinclude/efi/ \
		-Iinclude/efi-mix-ins/ \
		-I submodules/edk2/MdePkg/Include/ \
		<<EOF
#include "include/edk2-includes.h"
EOF
}

get_files() {
	local cpu x
	local -A files
	for cpu in "${CPUS[@]}" ; do
		for x in $(run_gcc "-DMDE_CPU_${cpu}")
		do
			if [[ "${x}" =~ ^submodules/edk2/ ]] ; then
				files["${x}"]=1
			fi
		done
	done
	for x in ${!files[*]} ; do
		echo "${x}"
	done
}

get_commit_id() {
	cd "${1}"
	git log --pretty='tformat:%h' -1
}

make_edk2guids() {
	cat > crte/efiguids.c <<EOF
// SPDX-License-Identifier: BSD-2-Clause-Patent
/*
 * efiguids.c - initializers for the guids edk2 declares
 */
#include <internals.h>

$(find submodules/edk2/ -name '*.dec' -print0 \
	| xargs -r -0 grep -h 'Guid\s*=\s*{' -- \
	| sed \
		-e 's,^\s*,EFI_GUID ,' \
		-e 's,\s\+, ,g' \
		-e 's,\s*=\s*\(.*\), = \L\1,' \
		-e 's,\s*{\s*, { ,g' \
		-e 's,\s*}\s*, },g' \
		-e 's/\s*,\s*/, /g' \
		-e 's,} }\s*;*\s*#.*$,} };,' \
		-e 's, } }$,&;,' \
	| sort -u)
EOF
	git add crte/efiguids.c
}

main() {
	find include/efi/ -type f -exec git rm {} \;

	# some git versions will have removed all the directories, but I don't
	# know if all of them will, and I'm too lazy to check.  Just mkdir it
	# before trying to remove the excess directories.
	mkdir -p include/efi/
	find include/efi/ -type d \
		-wholename include/efi/ -prune\
		-o -exec rmdir {} \;

	local -a oldfiles
	mapfile -t oldfiles < <(get_files)

	local oldfile newfile newdir
	set -x
	for oldfile in "${oldfiles[@]}" ; do
		newfile="${oldfile/submodules\/edk2\/MdePkg\/Include\//include\/efi\/}"
		newdir="${newfile%/*}"
		mkdir -vp "${newdir}"
		ln -v "${oldfile}" "${newfile}"
	done
	find include/efi/ -type f -exec git add {} \;

	make_edk2guids

	local commitid
	commitid=$(get_commit_id submodules/edk2)

	git commit -m "Update UEFI includes" -m "These are from edk2 commit ${commitid}" --no-edit -s
}

main "${@}"
